version: "3"

services:
  api:
    restart: always
    container_name: api
    build:
      context: ./core
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    volumes:
      - ./core:/home/node/meal-api
    environment:
      NODE_ENV: "development"
    networks:
      - backend
  db:
    restart: always
    container_name: database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
      MYSQL_DATABASE: "meal_db"
    ports:
      - "3306:3306"
    volumes:
      # - "data_mysql:/var/lib/mysql"
      - "./mysql/conf.d:/etc/mysql/conf.d"
    networks:
      - backend
  # redis:
  #   restart: always
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - backend
volumes:
  data_mysql:
networks:
  backend: