version: "3"

services:
  app:
    restart: always
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "8080:8080"
    depends_on:
      - "api"
    volumes:
      - ./app:/home/node/meal-app
    environment:
      NODE_ENV: "development"
    networks:
      - frontent
  api:
    restart: always
    container_name: api
    build:
      context: ./core
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - "db"
    volumes:
      - ./core:/home/node/meal-api
    environment:
      NODE_ENV: "development"
    networks:
      - backend
      - frontent
  db:
    restart: always
    container_name: database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
      MYSQL_DATABASE: "meal_db"
    ports:
      - "3306:3306"
    volumes:
      - ~/data/mysql:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - backend
  # redis:
  #   restart: always
  #   image: redis:alpine
  #   container_name: redis
      # volumes:
      #   - ~/data/redis:/var/lib/redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - backend
volumes:
  data:
networks:
  backend:
  frontent: