version: "3"

services:
  api:
    restart: always
    container_name: api
    build:
      context: ./core
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    volumes:
      - ./core:/usr/src/app
    environment:
      NODE_ENV: development
      MYSQL_DATABASE: meal_db
      MYSQL_ROOT_PASSWORD: 123123
    networks:
      - backend
  db:
    restart: always
    container_name: database
    image: "mysql:latest"
    ports:
      - "3306:3306"
    volumes:
      - data_mysql:/var/lib/mysql
    networks:
      - backend
volumes:
  data_mysql:
networks:
  backend:
